# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing
exclude:
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - create_entries.py
  - _config.example.yml
  - screenshot.png

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  location:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talks
  - scope:
      path: ""
      type: speakers
    values:
      layout: speakers
  - scope:
      path: ""
      type: location
    values:
      layout: location

# Theme default values
conference:
  lang: en

  speakers:
    show_firstname: true

  program:
    time_steps: 15
    show_alltimes: true
